"""Add OAuth tables for Claude Desktop integration

Revision ID: 8139e278e1d3
Revises: 45d413cc0184
Create Date: 2025-07-03 20:48:40.527167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8139e278e1d3'
down_revision = '45d413cc0184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'approval_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint('fk_users_approved_by', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_approved_by', 'users', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'approval_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###